# Недоделан и пока не испытывался.
# Скорее задел на будущее, тем более еще не известно,
# где будет сервер аутентификации, может вообще на другой машине.
networks:
  phobos-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-phobos
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-phobos-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - phobos-network

  eureka:
    container_name: eureka-server
    build:
      context: ../Eureka-server
    ports:
      - "7777:7777"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:7777/eureka
    depends_on:
      - mysql
    networks:
      - phobos-network

  auth:
    container_name: auth-server
    build:
      context: ../Auth-server
    ports:
      - "8090:8090"
    environment:
      - OAUTH2_ISSUER_URI=http://192.168.1.7:8090
    #  http://auth-server:8090
    depends_on:
      - eureka
    networks:
      - phobos-network

  gateway:
    container_name: gateway-server
    build:
      context: ../Gateway-server
    ports:
      - "8080:8080"
    environment:
      - OAUTH2_ISSUER_URI=http://auth-server:8090
      - EUREKA_SERVER_URL=http://eureka-server:7777/eureka
      - OAUTH2_REDIRECT_URI=http://192.168.1.7:8090/login/oauth2/code/apm-client
    depends_on:
      - auth
    networks:
      - phobos-network

  transfer-service:
    container_name: transfer-service
    build:
      context: ../Transfer-service
    ports:
      - "9050:9050"
    environment:
      - OAUTH2_ISSUER_URI=http://auth-server:8090
      - EUREKA_SERVER_URL=http://eureka-server:7777/eureka
    depends_on:
      - gateway
    networks:
      - phobos-network


volumes:
  mysql-phobos-data:
