POST http://localhost:9080/api/storage/schedule
Authorization: Bearer eyJraWQiOiJkNTU0MDIzOC1hOWJiLTQ1YWYtODljNi1mMWQyNWVhMWNiOTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzMzNDM5NzQzLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzMzNDQxNTQzLCJpYXQiOjE3MzM0Mzk3NDMsImp0aSI6IjUzNWZkNWZiLTU0ZDMtNDg0OC1hMGIzLTMyN2YyYzUzNDQ3OCIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.prIjKyk3RtzusA39WlWeC-DwQuW4kvlit2iGanyArkk_8lwSF9ngoyX4HP0qAQkMOKDrnc3Obgb_7Jfrn6R3wt7w34Z8WNtVvYoXRz8W2uOpfEYepMH1b9Q779oVqeNhx-9oegnj0f1bU4qIdV4Olyd0ioClbNI2NqbQtiJJ-XYI_OJpgCTXZRKZWNtcMiQb6K7EHILQdA3220LkGxZju3WUo0eAueJUJN3UcD_UPBBNNdEoAie6rkzU_qupL2Ap_rjxLtuskeuf7XdVOkDMbBiUdwo7dY3S4rHFb0op0KPIyY1Dc_BbMCvEsvYdFgHkNpdUBu3q4jwIoZqDJTlHAg
Content-Type: application/json

{
  "scheduleDetails": "Сб: 6.00 - 15.00"
}
