DELETE localhost:9080/api/storage/schedule?id=2
Authorization: Bearer eyJraWQiOiJkNTU0MDIzOC1hOWJiLTQ1YWYtODljNi1mMWQyNWVhMWNiOTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzMzNDQwMTAzLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzMzNDQxOTAzLCJpYXQiOjE3MzM0NDAxMDMsImp0aSI6IjkyNDg3NTU2LTMwNjItNDdkZS05OTNkLTBjZWUwYTJlZDMwNiIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.mhwoad1Xa9pVtQEsWRUT_Gw1GJWueqMsK2uZoYkxDiPf30D3qJCPHg_sRtDOoqALVJWwdZf3nU8-852XuNBIOzX0yTpRSyA2h1MSp3Lgb8rTlMtGKpuQnU_9DCfSW739hPfezT85SbOcYBW1YGrUJFCgIJ1h2mwwXNXUfN2IJEeaNY9XiwJ53E0QRiUXi2DidWilvUj71Km0Ue1BkhxetsoT7FjWrRkAVDXMPL4QrBMs2xtCtN7fYe4bFxE1j7z7FlG-k8FAiiBJeSdK8w1skG3NfHo4hCxCi7rFjXzbW1xAeZD7y5BSwBpa612JG6mGWB4-ofsc4u1NdSJeZkbVrA
