POST http://localhost:9070/api/logger/read
Authorization: Bearer eyJraWQiOiJkNTk5M2EzNi04M2RhLTQxYTUtYTE2ZC1jODcwODE4ZTRlZmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0Nzg1NzU0LCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzM0Nzg3NTU0LCJpYXQiOjE3MzQ3ODU3NTQsImp0aSI6ImFkZTQwMDU3LWU0MjEtNDAzMi1hZmMxLTYzZDE5Mjk1OGI3ZCIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.R021bfgj2uM88RUO16tvBdLv8_OgkMktIrszPkCe0DqQYxtFEt6sawOKg15UcebJoGVtXdRrer4mBX9w19zqKtRuw6pBmvFsndNeklfFyR0KzCHbp9Ai7isVS_QI-FFurCImy82TPZsTXCJuLkAXzZxL6AagPRlSeJJmQmF0qV496J-GHPQ3W2K3-jBzladY0BFedazEM03Ohp9yJmvbdtCD-e9mRmUi3htCwwS4taV60YdZokpEjF3YC__D9r-zo22hLfsWJ9Z4398GIqgJg-qQBU2yIvBtDcNQTiXLempi6YJB2gh6R1XWLH8Sqw3sU7CZjnzLY8AR8PmojiTV0A
Content-Type: application/json

{
  "repeater": 1,
  "key": -1,
  "from": "2024-11-28T11:22:41.207658",
  "to": "2024-11-28T21:22:41.207658"
}
