POST http://localhost:9010/api/transfer/awp/send-to-dev
Authorization: Bearer eyJraWQiOiIyZWFkODBmYy1mNmM3LTQzOTktOWMyZC1hMGNjOTA4NzM3YjYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzMyNjkxNTU0LCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzMyNjkxODU0LCJpYXQiOjE3MzI2OTE1NTQsImp0aSI6Ijk4MWY0ZGIzLTI4MTktNDY4NS04MTZjLTcyNzEwZjJkMGIwNSIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.BNsvRcgJZXBvzr6hQ_cxPjB_039xPhUPt0ppMwItlaYk4zx-EWd94Yb8gka8KAU2YBHxh3MjVhJT1o7qtm5tAiB1eyID9m-lXsF_8oTCQQ9MEiZWzr3UCYY9H_3Dc_kFG4GHEBe9CTOQuAvTgQtIvp7erldCpNNOzZ9aB2fIukcQhbfTE-akn6z5MIoSZi_13uAQIViBk969BGkLBYpPlhvj3SceDuwUvx4mEZrEQfS3hx-xe6QEUqOsKtIkZcNSouW2ujtODUWP99CCBQ2ifI9AMVHpt9LifB9svu91dftVsAccZ_Z4_VtwQzhBcssnPohBUEpM_LxEQSsZiK9WtA
Content-Type: application/json

{
  "repeater": 1,
  "key": 103,
  "code": 112
}
